services:
  - type: cron
    name: erp-agent
    schedule: "0 17 * * *"  # runs daily at 5 PM IST
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: your_account_sid
      - key: TWILIO_AUTH_TOKEN
        value: your_auth_token
      - key: TWILIO_PHONE
        value: your_twilio_number
      - key: RECEIVER_PHONE
        value: your_verified_number
      - key: ERP_USERNAME
        value: your_erp_username
      - key: ERP_PASSWORD
        value: your_erp_password
    buildCommand: ""
    startCommand: "python main.py"
