name: Daily Assignment Reminder

on:
  schedule:
    - cron: '30 11 * * *'  # Runs every day at 5:00 PM IST (11:30 AM UTC)
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    env:
      USERNAME_: ${{ secrets.USERNAME_ }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TO_WHATSAPP: ${{ secrets.TO_WHATSAPP }}
      FROM_WHATSAPP: ${{ secrets.FROM_WHATSAPP }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run assignment reminder script
        run: python main.py
